---
title: "presentation_slides"
format: html
---

## Topic and Motivation




---
## Research Question

**Initial Question:**
  - Are gallstone more prevelant than among patients with comorbidities compared to those without comorbidities? Does comorbidity predict gallstone?

**Refined Question:**
  - How do clinical and body composition variables influence the probability that a patient has gallstones?

---
## Why would we care?

- Gallstones are a common digestive conditions affecting millions, which can lead to serious complications is untreated
- Understanding risk factors helps:
  - Early detection
  - Better clinical decision making 
- We were interested in whether comorbidity predicts gallstones
- Goal: Our goal is to use Bayesian modeling (logistic regression model) to estimate **probability of gallstones** 

---

## Dataset

- Data: Gallstone dataset (health/ body composition)
- Source: UCI Irvine Machine Learning Repository
  - Contains clinical data collected from the Internal Medicine Outpatient Clinic of Ankara VN Medical Park Hospital in Turkey
  - Contains information on 319 patients, of whom 161 were diagnosed with gallstone disease
  - Contains 38 variables describing patient health and characteristics
- Observations: Patients with various clinical measurements 

**Key Variables**
- Outcomes: Gallstone Status(gallstone / 1 = yes, 0 = no)
- Predictors:
  - Vitamin D (vita_b)
  - Bone Mass (bone_mass)
  - CRP (crp)
  - Intracellular water (icw)
  - Hemoglobin (hgb)
  - Comorbidity (comorbid)

---

## Data Cleaning

- We renamed the variables for clarity
- We converted variables to binary:
  - Gallstone (reserved coding)
  - Comorbidity → 0/1
    - 0 = no comorbidity
    - 1 = at least one comorbidity
- Ensure the consistency for modeling 

**Why is this important?**
- Logistic regression requires correct outcome coding
- To prevent outcome interpretation

---

## Exploratory Data Analysis (EDA)

**Key Findings:**
- The gallstone outcome is relatively balanced and can be analyzed as a binary variable
- Comorbidity shows a weak relationship with gallstones 
  - Comorbidity did not strongly separate patients with and without gallstones
  - Comorbidity may not be a strong stand alone predictor of gallstone status
- Higher correlation with gallstone status:
  - Vitamin D
  - CRP
  - Bone mass
  - Lean mass
  - BFR

**Conclusion:**
- We decided to shift focus away from comorbidity and toward other predictors that appeared to have stronger relationships with gallstone status

---

## Model Choice 
We use **Bayesian Logistic Regression**

Why?
- Outcome is binary
- Estimates probability directly
- Allows use of prior knowledge
- Provides uncertainty via posterior distributions
And:
- Bayesian methods let us:
  - include prior information
  - quantify uncertainty with posterior distributions and credible intervals

## Model Setup

\[
\text{logit}(p_i) = \beta_0 + \beta_1(\text{vita\_d}) + \beta_2(\text{bone\_mass}) + \beta_3(\text{crp}) + \beta_4(\text{icw}) + \beta_5(\text{hgb})
\]

## Model Comparision

We have tested with 6 different models containing the different amount of predictors:








